package trader;

import org.eclipse.collections.impl.map.mutable.primitive.IntObjectHashMap;

public class TraderNames {


	
	
	public static final String[] names = new String[]{
		"Novak Djokovic",
		"Rafael Nadal",
		"Roger Federer",
		"Dominic Thiem",
		"Stefanos Tsitsipas",
		"Kei Nishikori",
		"Alexander Zverev",
		"Karen Khachanov",
		"Daniil Medvedev",
		"Kevin Anderson",
		"Fabio Fognini",
		"Juan Martin del Potro",
		"Roberto Bautista Agut",
		"Borna Coric",
		"John Isner",
		"Marin Cilic",
		"Nikoloz Basilashvili",
		"David Goffin",
		"Milos Raonic",
		"Gael Monfils",
		"Felix Auger-Aliassime",
		"Stan Wawrinka",
		"Diego Schwartzman",
		"Guido Pella",
		"Taylor Fritz",
		"Matteo Berrettini",
		"Nick Kyrgios",
		"Dusan Lajovic",
		"Benoit Paire",
		"Lucas Pouille",
		"Fernando Verdasco",
		"Denis Shapovalov",
		"Kyle Edmund",
		"Gilles Simon",
		"Jan-Lennard Struff",
		"Cristian Garin",
		"Laslo Djere",
		"Alex de Minaur",
		"Radu Albot",
		"Pierre-Hugues Herbert",
		"Sam Querrey",
		"Frances Tiafoe",
		"Reilly Opelka",
		"Mikhail Kukushkin",
		"Joao Sousa",
		"Jordan Thompson",
		"Lorenzo Sonego",
		"Hubert Hurkacz",
		"Pablo Cuevas",
		"Pablo Carreno Busta",
		"Filip Krajinovic",
		"Albert Ramos-Vinolas",
		"Daniel Evans",
		"Grigor Dimitrov",
		"Marton Fucsovics",
		"Casper Ruud",
		"Juan Ignacio Londero",
		"Miomir Kecmanovic",
		"Ugo Humbert",
		"Jo-Wilfried Tsonga",
		"Marco Cecchinato",
		"Cameron Norrie",
		"Federico Delbonis",
		"Nicolas Jarry",
		"John Millman",
		"Richard Gasquet",
		"Feliciano Lopez",
		"Pablo Andujar",
		"Adrian Mannarino",
		"Andrey Rublev",
		"Alexander Bublik",
		"Tennys Sandgren",
		"Philipp Kohlschreiber",
		"Jeremy Chardy",
		"Roberto Carballes Baena",
		"Yoshihito Nishioka",
		"Ricardas Berankis",
		"Andreas Seppi",
		"Stefano Travaglia",
		"Martin Klizan",
		"Ivo Karlovic",
		"Leonardo Mayer",
		"Corentin Moutet",
		"Thomas Fabbiano",
		"Peter Gojowczyk",
		"Robin Haase",
		"Alexei Popyrin",
		"Marius Copil",
		"Hugo Dellien",
		"Prajnesh Gunneswaran",
		"Aljaz Bedene",
		"Bradley Klahn",
		"Steve Johnson",
		"Lloyd Harris",
		"Bernard Tomic",
		"Mackenzie McDonald",
		"Soonwoo Kwon",
		"Brayden Schnur",
		"Marcel Granollers",
		"Kamil Majchrzak"
	};
   
}
