/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DEXOrderbookTemplate;

public class DEXOrderbookTemplate {
    
	
	
	
	public boolean someLibraryMethod() {
        return true;
    }
}
